{% set version = "5.10.0" %}
{% set pscom_version = "5.8.0" %}

package:
  name: psmpi
  version: {{ version }}

source:
  - url: https://github.com/ParaStation/psmpi/archive/refs/tags/{{ version }}-1.tar.gz
    sha256: c05a0281934dc54dc1178df997481a9be4b5b3cc7d5aa515f55d9f7df3f491dc
    folder: psmpi
  - url: https://github.com/ParaStation/pscom/archive/refs/tags/{{ pscom_version }}-1.tar.gz
    sha256: e07759bf6efb99c15e9e2a77f32a27af71e0e0438813eaa589ab03d3d0683eca
    folder: pscom

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - cmake
    - libtool
    - make
  host:
    - libhwloc
    - libpmix-devel 
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - libhwloc
    - libpmix

test:
  files:
    - hello_world_mpi.f90
  commands:
    - mpichversion
    - mpifort -o hello_world_mpi hello_world_mpi.f90
    - ./hello_world_mpi

about:
  home: https://github.com/ParaStation/psmpi
  license: QPL-1.0
  license_family: OTHER
  license_file: LICENSE
  summary: ParaStation MPI is an implementation of the Message-Passing Interface (MPI) Standard.
           Being an MPICH-derivative it bases on the MPICH-4.1.1 implementation.

extra:
  recipe-maintainers:
    - j34ni
