github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
  pkg_format: 2
conda_forge_output_validation: true
provider:
  linux_64: azure
  linux_aarch64: travis
build_platform:
  linux_64: linux_64
  linux_aarch64: linux_aarch64
test: native
